[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
aiogram = "^3.20.0.post0"
python-dotenv = "^1.1.0"
pydantic-settings = "^2.9.1"
deep-translator = "^1.11.4"
aiokafka = "^0.12.0"
